### ISSUE TITLE
KiCad plugin needs Java 17, but it generates a long misleading error message

### ISSUE THREAD

**Issue by tormyvancool** [freerouting/freerouting#151] opened 2022-11-01 11:20 UTC
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [x] What version of freerouting are you using? **v1.4.4 .EXE ando also a previous one in .JAR**
* [x] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit? **Windows 11 Pro 64bit**
* [x] What type of file are you working with? Can you attach the actual (DSN) file? **PCB files out of KiCAD (6.08 and 6.09).  No I can't due NDA**
* [x] Did you use any command line arguments? No
* [x] Can you post a screenshot of the problem? **yes here below**
* [ ] Can you include the latest, related log entries from the .log file?
* [x] Please list the detailed steps to reproduce the problem
* [x] What would you expect freerouting to do in this situation? Just be able to indicate where my Freerotue is located, since it's not on C driver at all.
* [x] Is fixing this issue critical for your work? **yes it is**

From inside the PCB of KiCAD I try to launch Freeroute clicking oth the button located on the main toolbar but I got this screenshot
So, I have to run Freeroute manually as I usually do. But if your plugin was working I could using from inside KiCAD directly

![image](https://user-images.githubusercontent.com/32305535/199221093-fcf3acb1-6b83-414e-a4d4-10de43999d09.png)

**Comment by andrasfuchs** [comment] 2022-11-01 12:18
Yes, looking at your screenshot the mixing of `\` and `/` characters in the path doesn't look right.
First I thought that we need to change [the plugin script](https://github.com/freerouting/freerouting/blob/master/integrations/KiCad/kicad-freerouting/plugins/plugin.py) to use the correct one depending on the platform, but as far as I can see we use `os.path.join` which should take care of this. 
It needs further investigation.

**Comment by tormyvancool** [comment] 2022-11-24 10:12
The script is in facts unusable. I had to uninstall your package. Sorry for this.
When ther ewill be a working/stable one I will be happy to install it

**Comment by andrasfuchs** [comment] 2023-01-03 14:12
Sorry, I understand your frustration, the error message you got isn't really helpful.

The reason was that you had Java 8 installed, but Freerouting needs Java 17.

**Comment by tormyvancool** [comment] 2023-01-03 14:27
> 

Well normally I perform updates each time the system requires. So, if Java17 is required but I have Java8 it means i didn't get any updates from the 8 on ... where do I find it so I iwll see if ever the issue is popping up again?

**Comment by andrasfuchs** [comment] 2023-01-03 16:32
Hmm, that's strange. Is it possible the you have both Java JRE 8 and 17 installed? In that case I can imagine that the default Java path is set to 8, and not 17. I guess KiCad tries to run freerouting by calling the default Java JRE (and not the latest one installed). Otherwise I think it should work!

In any case, you can download Java 17 from here: https://adoptium.net/temurin/releases/

**Comment by tormyvancool** [comment] 2023-01-03 16:53
> Hmm, that's strange. Is it possible the you have both Java JRE 8 and 17 installed? In that case I can imagine that the default Java path is set to 8, and not 17. I guess KiCad tries to run freerouting by calling the default Java JRE (and not the latest one installed). Otherwise I think it should work!
> 
> In any case, you can download Java 17 from here: https://adoptium.net/temurin/releases/

Well not I have only the 8:
![image](https://user-images.githubusercontent.com/32305535/210403388-0821cb9a-9571-4dff-8aed-28914f5ef85c.png)

**Comment by tormyvancool** [comment] 2023-01-03 16:58
Oh damn ... 
![image](https://user-images.githubusercontent.com/32305535/210404301-1b2f324a-dd10-401e-8802-157f34195da5.png)

**Comment by andrasfuchs** [comment] 2023-01-03 18:22
I made the publication of the new version an hour ago, so version 1.6.5 should be there in the KiCad Plugin Manager in a few hours. I hope that will work, but let me know if it still doesn't!

Sorry for the problems, and thank you for your reports!

**Comment by tormyvancool** [comment] 2023-01-03 21:52
> I made the publication of the new version an hour ago, so version 1.6.5 should be there in the KiCad Plugin Manager in a few hours. I hope that will work, but let me know if it still doesn't!
> 
> Sorry for the problems, and thank you for your reports!

I installed this https://www.oracle.com/java/technologies/downloads/#java17 but your package still not available, for the time being

**Comment by andrasfuchs** [comment] 2023-01-03 22:17
It should be there soon, but it's out of my control when.

Until then you can download it [from here](https://github.com/freerouting/freerouting/blob/master/integrations/KiCad/kicad-freerouting-1.6.5.zip?raw=true) and choose `Install from File...` in the KiCad Plugin Manager, if you like to try it.

**Comment by tormyvancool** [comment] 2023-01-04 16:41
> It should be there soon, but it's out of my control when.
> 
> Until then you can download it [from here](https://github.com/freerouting/freerouting/blob/master/integrations/KiCad/kicad-freerouting-1.6.5.zip?raw=true) and choose `Install from File...` in the KiCad Plugin Manager, if you like to try it.

I was constrained to install it from file ... since it's not yet available on the plugin manager.

now it damn works :-)  BUT:

1 . Into the toolbar there is not a distinctive icon
![image](https://user-images.githubusercontent.com/32305535/210604791-34cf574b-8488-4cbb-a88f-b745758f8115.png)

**Comment by andrasfuchs** [comment] 2023-01-06 09:08
I'm glad it finally works! :)

Yes, good point, we'd need to replace that icon!

**Comment by tormyvancool** [comment] 2023-01-06 09:46
> I'm glad it finally works! :)
> 
> Yes, good point, we'd need to replace that icon!

I think they must also to improve their policies for the updates. If anyone tries to update the package by the package manager, even after days, it returns error.

![image](https://user-images.githubusercontent.com/32305535/210975190-d7a4a8fc-3e77-46c3-ba6a-0a1bd4241060.png)

**Comment by andrasfuchs** [comment] 2023-01-06 09:56
That is odd. Can you open the URL directly in your browser?
https://github.com/freerouting/freerouting/raw/master/integrations/KiCad/kicad-freerouting-1.6.5.zip

**Comment by andrasfuchs** [comment] 2023-01-06 17:51
I added the Java version check and fixed the toolbar icon for the KiCad plugin.

Here is [my merge request](https://gitlab.com/kicad/addons/metadata/-/merge_requests/151), so if/when they merge and publish it, these will be fixed.

**Comment by tormyvancool** [comment] 2023-01-06 23:53
> That is odd. Can you open the URL directly in your browser? https://github.com/freerouting/freerouting/raw/master/integrations/KiCad/kicad-freerouting-1.6.5.zip

Yes I could do it in the broswer without issue

**Comment by tormyvancool** [comment] 2023-01-06 23:56
> I added the Java version check and fixed the toolbar icon for the KiCad plugin.
> 
> Here is [my merge request](https://gitlab.com/kicad/addons/metadata/-/merge_requests/151), so if/when they merge and publish it, these will be fixed.

I re-installed it form the link you gave me right above, but the icon still the generic one
![image](https://user-images.githubusercontent.com/32305535/211118848-0f3e3e0f-2f9d-443d-8b5b-82a4d395254f.png)

**Comment by andrasfuchs** [comment] 2023-01-08 11:11
The new, fixed version got published to the KiCad Plugin Manager only an hour ago. Could you try 1.6.6?

![image](https://user-images.githubusercontent.com/910321/211192750-ba632442-9c94-4dfb-9ead-da06f1c4e1a1.png)

![image](https://user-images.githubusercontent.com/910321/211192795-b6f65d9c-bb1c-4f0a-829d-95b258a1a35d.png)

![image](https://user-images.githubusercontent.com/910321/211192862-43567e50-05ef-4be5-8334-689308034188.png)

**Comment by tormyvancool** [comment] 2023-01-09 10:45
This is what I get:

![image](https://user-images.githubusercontent.com/32305535/211290501-e4d6515b-0f16-412e-bc16-b01c46daae08.png)

**Comment by andrasfuchs** [comment] 2023-01-09 12:49
I tried installing it from multiple countries (by using VPN) using KiCad 6.0.5, and they all worked.

It looks like it's out of my control at this point, it might be a bug in KiCad 6.0.10 or a network configuration you have.

If anyone else reads this, please comment below if you can or can't download the archive (like @tormyvancool) so that we can continue the investigation.

**Comment by tormyvancool** [comment] 2023-01-09 14:03
> I tried installing it from multiple countries (by using VPN) using KiCad 6.0.5, and they all worked.
> 
> It looks like it's out of my control at this point, it might be a bug in KiCad 6.0.10 or a network configuration you have.
> 
> If anyone else reads this, please comment below if you can or can't download the archive (like @tormyvancool) so that we can continue the investigation.

I opened a thread on the forum, referring to this issue. Hopefully they can check and come up with a solution.

https://forum.kicad.info/t/plugin-manager-issue-downloading-plugins/39460/15

**Comment by rei-vilo** [comment] 2023-01-16 19:46
Same problem here, `OpenJDK 64-Bit Server VM Temurin-17.0.5+8` installed but the plug-in complains about the missing Java 17 JRE.

![Capture 2023-01-16 20-43-24](https://user-images.githubusercontent.com/951776/212755271-749f40be-76ed-403f-a844-95fa608d54ed.png)

```
$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

Kicad is release `6.0.10`

```
Application: KiCad

Version: 6.0.10, release build

Libraries:
	wxWidgets 3.2.1
	libcurl/7.86.0-DEV OpenSSL/3.0.7 zlib/1.2.12 nghttp2/1.51.0

Platform: Linux 6.0.0-0.deb11.2-amd64 x86_64, 64 bit, Little endian, wxGTK, gnome, wayland

Build Info:
	Date: Jan 14 2023 11:12:49
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.81.0
	OCC: 7.6.3
	Curl: 7.86.0-DEV
	ngspice: 38
	Compiler: GCC 12.1.0 with C++ ABI 1017

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by andrasfuchs** [comment] 2023-01-17 17:05
@rei-vilo Thanks for the report, I'll need to look into this, but I can't in the next few weeks.

Is the java executable part of the PATH variable, so can it be executed from anywhere on your system? If yes, then I suspect that it's a Linux specific issue that I need to fix later.

Until then you can try version 1.6.5, they are basically the same except the Java version checking during the plugin installation.

**Comment by rei-vilo** [comment] 2023-01-17 18:02
Thank you for your prompt answer! Yes, the path to `java` is included in the `PATH` variable.

```
$ which java
/usr/bin/java
$ echo $PATH
/home/USER/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/USER/.local/bin
```

There is no hurry: I am using FreeRouting manually. Good luck!

**Comment by tormyvancool** [comment] 2023-01-29 12:13
With version 6.0.11 it's solved ... I hope still solved with the 7 ...

**Comment by andrasfuchs** [comment] 2023-02-07 19:32
@rei-vilo Could you confirm that it works for you as well with KiCad 6.0.11?

If it still not doesn't, could you run the `java -version` command, and tell me what the exact output that you have?

**Comment by rei-vilo** [comment] 2023-02-07 20:20
Thank you for coming back. Kicad is now `Version: 6.0.11, release build` but the plug-in still complains about Java 17.
 
```
$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)

$ which java
/usr/bin/java

$ echo $PATH
/home/USER/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/USER/.local/bin

/home/USER/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/USER/.local/bin
```

**Comment by andrasfuchs** [comment] 2023-02-07 23:42
@rei-vilo I modified the regular expression used for version detection and I have just uploaded a file that can be run separately to check the Java version. Could you help me by running this small python script on your machine?

Here is [the checkjava.py](https://github.com/freerouting/freerouting/blob/master/integrations/KiCad/checkjava.py), you can run it by the `python -c "import checkjava; checkjava.get_java_version()"` command if you have Python 3 installed.

Please send me back the exact output you have, thank you!

**Comment by rei-vilo** [comment] 2023-02-08 08:00
Here is the result:

```
$ python -c "import checkjava; checkjava.get_java_version()"
openjdk version "17.0.6" 2023-01-17
17.0.6
```

**Comment by andrasfuchs** [comment] 2023-02-08 09:11
Great, thank you!

**Comment by rei-vilo** [comment] 2023-02-13 16:32
I tested the new release `1.7.0` on Kicad `7.0`. 

I am using [Kicad installed as FlatPak](https://www.kicad.org/download/flatpak/) on Debian 11.

Alas, the same error message appears. 

1. I edited line

https://github.com/freerouting/freerouting/blob/e7ab5f9064b9453103693a84201f1e0cfc30a83d/integrations/KiCad/kicad-freerouting/plugins/plugin.py#L262

to
 
```
        return "17.0.6"
```

2. I cleaned the `__pycache__` and called the plug-in again.

![FreeRouting1 7onKicad7 0](https://user-images.githubusercontent.com/951776/218514108-cf88ca9f-7804-4919-b942-c8ed452b30df.png)

3. I used FlatSeal to edit the authorization and allow access to system files, and executables. 

4. I also listed `/usr/bin/java` in specific files.

None of the actions below solved the issue. 

It looks like Kicad installed with FlatPak and the plug-in do not have access to the system.

**Comment by rei-vilo** [comment] 2023-02-13 16:43
Instead of using [Kicad installed as FlatPak](https://www.kicad.org/download/flatpak/), I took the [back-port version for Debian](https://www.kicad.org/download/debian/).

Everything works fine now: I am calling FreeRouting from the plug-in menu of Kicad PCB.

**Comment by andrasfuchs** [comment] 2023-02-15 22:30
Interesting! We might have a new problem with KiCad 7 or Flatpak?

There are a few more issues related to KiCad plugin (#169 #168 and #170), let's get them fixed first, so if it's stable with KiCad 6, I can start testing with KiCad 7.

Thanks for the details @rei-vilo!

**Comment by rei-vilo** [comment] 2023-02-16 09:55
You're welcome! 

> Interesting! We might have a new problem with KiCad 7 or Flatpak?

As applications bundled by FlatPak run in a sandbox, I suspect this is the cause of the issue, even though I had authorised the access to the system files and Java in particular.

It might be worth asking FlatPak and Kicad about how the plug-ins of an application are managed.

**Comment by rei-vilo** [comment] 2023-02-16 09:56
You're welcome! 

> Interesting! We might have a new problem with KiCad 7 or Flatpak?

As applications bundled by FlatPak run in a sandbox, I suspect this is the cause of the issue, even though I had authorised access to the system files and Java in particular.  

It might be worth asking FlatPak and Kicad about how the plug-ins of an application are managed.

**Comment by retiredfeline** [comment] 2023-05-12 09:55
From what I understand of flatpaks, and having built one myself for another project, as well as some searching of the relevant *stacks, it is indeed the sandbox that prevents execution of Java programs using the system's Java environment.

Unfortunately that's not the whole story. There is an openjdk extension to the freedesktop runtime (one of three major runtimes flatpaks can be built for) but it's for the **Sdk**! That is to say, it's only useful to the person building the KiCad flatpak to add Java execution. It's not possible to add a Java "runtime" to an existing flatpak installation.

So, sorry, the answer is don't use the KiCad flatpak if you want to use freeRouting ahd hence Java. Use the native packages for your distro.

**Comment by andrasfuchs** [comment] 2023-05-12 12:37
Thank you for the insight @retiredfeline!
I have no experience with Flatpak, so it's probably a noob questions, but what do you think, could KiCad decide to allow Java execution in their Flatpak container if they changed their Flatpak settings/setup?

Btw, what the most recent plugin installer script does is that if Java can't be found or it's not accessible (because of Flatpak) it tries to install JRE 17 into the system temp directory on the fly and run the Freerouting app using that installation. 

I don't know yet, if it works, we'll see when the community provides some feedback after the next release.

**Comment by retiredfeline** [comment] 2023-05-12 12:47
Hi, this is what would have to happen:

- The volunteer building the flatpak (not the KiCad project or the developers) would have to add the openjdk extension to their Sdk for building the flatpak. BTW, the openjdk extension is for the freedesktop Sdk, and I don't know if the GNOME Sdk supports the openjdk extension.
- The flatpak gets bloated because it's now carrying an openjdk runtime environment inside the flatpak so that the java interpreter can run inside the sandbox.

So I don't know if the flatpak packager would agree to that.

**Comment by retiredfeline** [comment] 2023-05-14 00:52
A long term development that might help is to enhance freeRouting to be able to be run as a service that accepts jobs and returns the result over the network. This would mean running headless and having no interactive control over the job. Something would have to be put in place to deal with jobs that won't terminate or take too long. But it would enable the service to be shared across many users without them having to install Java. It could be run on a powerful compute server.

This is just speculation and probably deserves a separate discussion, if at all.

**Comment by andrasfuchs** [comment] 2023-05-14 13:14
Yes, I agree. I had similar plans, but I had to realize that there is not enough community support at the moment to do the development. I'm the only maintainer, I work for free when I have a few days and it's just too big of a change without help.

I almost got a small team of Java developers from the University of Copenhagen to work on it as their assignment, so if any of you have connection to universities, telling them about Freerouting would be a great way to show your support! ;)

Here is the e-mail I wrote to them in 2022, feel free to use any part of it: https://github.com/freerouting/freerouting/discussions/193

**Comment by retiredfeline** [comment] 2023-05-14 13:46
If it's possible to make freeRouting run headless and unattended from the command line, I'd be willing to work on a Python server to accept input over the network, run freeRouting, and return the output over the network. This can then be converted to Java if desired later. Essentially doing as a server what a user does from the KiCad plugin.

**Comment by andrasfuchs** [comment] 2023-05-15 07:59
Sounds great!

We only have [a partial headless implementation](https://github.com/freerouting/freerouting/blob/master/src/main/java/app/freerouting/interactive/BoardHandlingHeadless.java), but scripting is still possible with the [command line arguments](https://github.com/freerouting/freerouting#using-the-command-line-arguments). If you set both the input (`-de`) and the output (`-do`) files Freerouting automatically loads the input file, does the routing, saves the output file and exits. Logs are written to both the console+stderr and into log files.

Is this enough, or you would need a truely headless execution? 
If you are willing to work on this, please open a new issue, so we can discuss the further details there.

Thank you for considering it!

**Closed** 2023-10-12 12:45 UTC
Labels: bug, help wanted, no-issue-activity
