### ISSUE TITLE
Request Windows 32 bit version 

### ISSUE THREAD

**Issue by lynchaj** [freerouting/freerouting#53] opened 2021-08-04 11:51 UTC
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [x] What version of freerouting are you using?  old Java based 1.2.43 (confirmed)
* [x] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?  Windows10, 32 bit with Java
* [x] What type of file are you working with? Can you attach the actual (DSN) file?  Multiple DSN files
* [x] Did you use any command line arguments? No
* [x] Can you post a screenshot of the problem? N/A, 64 bit Windows installer gives an error message and refuses to install
* [x] Can you include the latest, related log entries from the .log file? N/A
* [x] Please list the detailed steps to reproduce the problem N/A
* [x] What would you expect freerouting to do in this situation? Please post a Windows 32 bit build along side the 64 bit build or include dual 64 bit and 32 bit binaries in the Windows distribution package
* [x] Is fixing this issue critical for your work? No, but would be nice to use updated version of FreeRouting with updates

**Comment by lynchaj** [comment] 2021-08-04 13:00
Thank you for your consideration.  Much appreciated!

**Comment by andrasfuchs** [comment] 2021-09-19 15:47
I spent a few hours on our build scripts and the Windows x86 (32-bit) version are now available, you can download it from here:
https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

Could you test it and confirm that it works as expected on a 32-bit system?

**Comment by lynchaj** [comment] 2021-09-19 16:07
Hi Andras,
Thank you so much for making a 32 bit Windows version of FreeRouting. Unfortunately I get an error message (see attached image) and it does not install.

Thanks, Andrew Lynch

     On Sunday, September 19, 2021, 11:47:46 AM EDT, Andras Fuchs ***@***.***> wrote:  
 
 


I spent a few hours on our build scripts and the Windows x86 (32-bit) version are now available, you can download it from here:
https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

Could you test it and confirm that it works as expected on a 32-bit system?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lynchaj** [comment] 2021-09-19 16:10
Hi Andras,
Well, the attachment got stripped off my email. It was a PNG but it said "This installation package is not supported by this processor type. Contact your product vendor."

Hopefully this is easily fixable. Thank you! Andrew Lynch
     On Sunday, September 19, 2021, 12:07:54 PM EDT, lynchaj ***@***.***> wrote:  
 
 

 Hi Andras,
Thank you so much for making a 32 bit Windows version of FreeRouting. Unfortunately I get an error message (see attached image) and it does not install.

Thanks, Andrew Lynch

 On Sunday, September 19, 2021, 11:47:46 AM EDT, Andras Fuchs ***@***.***> wrote: 
 
 


I spent a few hours on our build scripts and the Windows x86 (32-bit) version are now available, you can download it from here:
https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

Could you test it and confirm that it works as expected on a 32-bit system?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andrasfuchs** [comment] 2021-09-19 16:15
Sure, no problem. 
Thanks for the feedback! I will probably need your help again if I have a newer version to test, because I don't have a 32-bit system. I'll let you know here when the new file is ready.

**Comment by lynchaj** [comment] 2021-09-19 16:18
Hi Andras
OK great! Looking forward to it

Thanks, Andrew Lynch     On Sunday, September 19, 2021, 12:15:11 PM EDT, Andras Fuchs ***@***.***> wrote:  
 
 


Sure, no problem.
Thanks for the feedback! I will probably need your help again if I have a newer version to test, because I don't have a 32-bit system. I'll let you know here when the new file is ready.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
     On Sunday, September 19, 2021, 12:15:11 PM EDT, Andras Fuchs ***@***.***> wrote:  
 
 


Sure, no problem.
Thanks for the feedback! I will probably need your help again if I have a newer version to test, because I don't have a 32-bit system. I'll let you know here when the new file is ready.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andrasfuchs** [comment] 2021-09-19 17:07
I know it's not ideal, but you can try to use the .jar release. If you [download that JAR file](https://github.com/freerouting/freerouting/releases/download/SNAPSHOT/freerouting-SNAPSHOT-2021-09-19_14-45-42.jar), and install [the 32-bit Java 11 runtime](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot#x32_win) on your machine, you should be able to run it.

For example, the following should work:
`java.exe -jar freerouting-executable.jar`

Could you get back to me if it works this way?

**Comment by lynchaj** [comment] 2021-09-19 18:32
Hi Andras,
OK, that worked. I downloaded the 32 bit Windows version of the OpenJDK JRE (29MB) and installed it. Then downloaded the FreeRouting snapshot. It ran right away in the new OpenJDK JRE like expected. Also my previous version of Java 8 and FreeRouting 1.2.43 Extra were not effected so they still run.

The new FreeRouting starts right up and loads designs no problem. However most of the time when I press the "autoroute" button on the top of the screen I get a message in the status bar on the bottom saying "autoroute interrupted, x connections incomplete" or something to that effect. Occasionally it seems to work but there must be some kind of bug still present. Other buttons on the top of the screen work fine like "zoom all" and "incompletes" so not sure what's happening with "autoroute"

On my computer the UI is plainly been updated to more recent standards and looks really nice. The FreeRouting application is basically the same. Possibly the autorouting and optimization seems to be going somewhat quicker but my computer is old and slow, Still any improvement, perceived or otherwise, is greatly appreciated!

Looks good! Thanks for making this work, I'll send more reports as I go.

Thanks, Andrew Lynch
     On Sunday, September 19, 2021, 01:07:21 PM EDT, Andras Fuchs ***@***.***> wrote:  
 
 


I know it's not ideal, but you can try to use the .jar release. If you download that JAR file, and install the 32-bit Java 11 runtime on your machine, you should be able to run it.

For example, the following should work:
java.exe -jar freerouting-executable.jar

Could you get back to me if it works this way?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andrasfuchs** [comment] 2021-09-20 21:04
Hi Andrew,

Yes, you are right about the looks, it hasn't been changed in ages. :)

The 32-bit MSI installer would be a lot trickier than I thought, and I already spent more time on it than I wanted, so if the workaround works then I will leave it like that. I added a new section about the problem to [our readme page here on GitHub](https://github.com/freerouting/freerouting#running-freerouting-on-32-bit-systems).

The interruption bug you mentioned is interesting. If you could reproduce it in a consistent way, that would be great. If you can, please open a new issue and attach the .DSN file that caused the trouble. Thank you!

I'll close this issue now.

**Closed by andrasfuchs** 2021-09-20 21:04 UTC
Labels: enhancement, help wanted
